serial_gas_node:
  ros__parameters:
    serial_port: /dev/ttyUSB0
    baud_rate: 9600
    parity: "none" # none/even/odd
    poll_interval_ms: 1000
    startup_timeout_seconds: 120
    fail_on_startup_timeout: false
    inter_request_delay_ms: 500
    response_timeout_ms: 1000
    alarm_repeat_seconds: 10
    temperature_offset_raw: 0                                     # 当前温度编码为raw/10，手册偏移编码为500
    max_retries_per_slave: 3
    debug_hex: true
    slave_ids: [1, 2, 3, 4, 5, 6]                                 # CO2、CO、O2、CH4、CO2、O3
    use_config_alarm_thresholds: true                             # false使用设备寄存器阈值，true使用配置覆盖阈值
    alarm_threshold_slave_ids: [1, 2, 3, 4, 5, 6]
    low_alarm_overrides: [500.0, 35.0, 23.5, 20.0, 1000.0, 0.2]   # [500.0, 35.0, 19.5, 20.0, 1000.0, 0.1]
    high_alarm_overrides: [1500.0, 75.0, 25.0, 50.0, 2000.0, 0.5] # [1500.0, 75.0, 23.5, 50.0, 2000.0, 0.5]
    gas_type_overrides: ["SF6", "CO", "O2", "CH4", "CO2", "O3"]
