serial_gas_node:
  ros__parameters:
    serial_port: /dev/ttyUSB0
    baud_rate: 9600
    parity: "none" # none/even/odd
    poll_interval_ms: 1000
    startup_timeout_seconds: 120
    fail_on_startup_timeout: false
    request_start_addr: 0
    request_count: 10
    inter_request_delay_ms: 500
    max_retries_per_slave: 3
    debug_hex: true
    slave_ids: [1]

http_gas_node:
  ros__parameters:
    gas_api_url: "http://192.168.2.180/spl"
    gas_threshold: 35.0
    consecutive_seconds: 4
    source_name: "http_spl"
